### ISSUE TITLE
Add locations

### ISSUE THREAD

**Issue by Ezague** [jonassvensson4/jsfour-criminalrecord#26]
Hello there! Nice script. I converted it to vRP and it works perfect! I just have one wish! Is there any way that I can add extra locations where I can use the criminal records? Would be very nice!

**Comment by jnsvns** [comment]
Of course, you just have to make some changes to the client.lua and the config.lua since it's only using the markers array. You would've to add new arrays inside the markers array with all the different locations. You would then need to loop through that array in the client.lua.

I should rewrite this resource client and server one day to get rid of ESX and clean it up. But for now you'll have to look at other resources for examples if you want to add this feature.

Good luck!
