### ISSUE TITLE
restart the resource

### ISSUE THREAD

**Issue by wanderrer** [jonassvensson4/jsfour-criminalrecord#27]
Hello,
Everything works fine, until I restart the resource. If I do that, the marker will not be display, there are no errors or anything. Number 2, how can I add more markers ? I want to add them to all the PD stations and jail. Dose the config allows array in array ? Thank you.

**Comment by jnsvns** [comment]
1. That's because it won't know if you've the police job or not: [client.lua:L36](https://github.com/jonassvensson4/jsfour-criminalrecord/blob/master/client.lua#L36). If you restart the resource you'll need to set your job as police even if you already have. I guess that's just how ESX works.

2. You'll have to tweak the client.lua file, it only reads one array at the moment. Just add a loop and it should be fine.
